name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: curriculum_vitae.tex
          latexmk_use_xelatex: true
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          path: curriculum_vitae.pdf
      - name: Check pdf file
        run: |
          file curriculum_vitae.pdf | grep -q ' PDF '
      - name: Upload file to repository
        run: |
          git config --global user.name "zoltanpm"
          git config --global user.email "zpm@zoltanpm.com"
          git add curriculum_vitae.pdf
          git commit -m "update cv pdf file"
          git push
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
